In [2]:
arr=[2,3,4,5]
print(arr*5)
arr=[x*5 for x in arr ] ## list comprehension
print(arr)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]
[10, 15, 20, 25]


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5,67])
arr1=arr1*5  ## broadcasting
print(arr1)

[  5  10  15  20  25 335]


## Ndarray

In [4]:
import numpy as np
# 1d Array
ara1=np.array([1,2,3,4,5]) 
print(type(ara1))
print(ara1.ndim)

#2d array
arra1=np.array([
               [1,2,3,4],
               [6,7,8,9]]
              )
print(arra1)
print(type(arra1))
print(arra1.ndim)
arra2=np.array([
    #1st floor
            [[1,2,3,4],
               [6,7,8,9]] ,
                ##2nd floor
                [[1,2,3,4],
               [6,7,8,9]],
               [[1,2,3,4],
               [6,7,8,9]]
])
print(type(arra2))
print(arra2.ndim)

<class 'numpy.ndarray'>
1
[[1 2 3 4]
 [6 7 8 9]]
<class 'numpy.ndarray'>
2
<class 'numpy.ndarray'>
3


## Array Attributes

In [5]:
#dimension
print(ara1.ndim)
print(arra1.ndim)
print(arra2.ndim)
#shape
print(ara1.shape)
print(arra1.shape)
print(arra2.shape)
#data type\
print(ara1.dtype)
print(arra1.dtype)
print(arra2.dtype)
#size
print(ara1.size)
print(arra1.size)
print(arra2.size)

1
2
3
(5,)
(2, 4)
(3, 2, 4)
int64
int64
int64
5
8
24


In [6]:
array=np.array([1,2,3])
print(array.dtype)
array2=np.array([1.5, 2.3, 4.5])
print(array2.dtype)

int64
float64


In [7]:
arr=np.array([1,2,34,4.5])
#upcasting
print(arr.dtype)

float64


In [8]:
arr=np.array([1,2,34,4.5, 'h']) ## unified
#upcasted to string
print(arr.dtype)

<U32


### selecting a data type of an array

In [11]:
arr=np.array([1,3,300], dtype=np.int8) #128 porjonto convert korte pare , exceed hoice oijonno error dekhai
print(arr.dtype)
print(arr)

OverflowError: Python integer 300 out of bounds for int8

In [10]:
arr=np.array([1,3,3.4, "hridoy"], dtype=np.float64) #string k float e convert korte parbe na oijonno error dekhai
print(arr)

ValueError: could not convert string to float: 'hridoy'

In [ ]:
arr=np.array([1,3,300], dtype="U32") 
print(arr.dtype)
print(arr)

In [ ]:
arr=np.array([1,3,300], dtype=np.int16) 
arr=arr.astype(np.int32)
print(arr.dtype)

In [ ]:
arr=np.array([1,3,300, True, 3.23, "Hridoy"]) 
print(arr.dtype)
print(arr)

### ndArray creation from existing data

In [ ]:
lst=[10,20,3,4,5,6,7,40.5]
arr=np.array(lst, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
lst=[10,20.5, True, "Mahmuduul"]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
lst=[[[1,2,3,4],[6,7,8,9]] ]

arr=np.array(lst)
print(type(arr))
print(arr.shape)
print(arr.dtype)

In [ ]:
#tuple
tp=(10,20,40)
arr=np.array(tp)
print(type(arr))
print(arr.dtype)
print(arr)

In [ ]:
#set
set={1,2,43,4,5}
arr=np.array(set)
print(type(arr))
print(arr.dtype)
print(arr)

In [ ]:
set={1,2,43,4,5}
arr=np.array(set, dtype="U32") ## DATA TYPE CONVERSION FROM OBJECT TO STRING
print(type(arr))
print(arr.dtype)
##arr=arr.astype(np.int16)
print(arr.dtype)
print(arr.size)
print(arr)

In [ ]:
set={1,2,43,4,5}
arr=np.array(list(set), dtype=np.int32) ##DATA TYPE CONVERSION FROM OBJECT TO STRING
print(type(arr))
print(arr.dtype)
arr=arr.astype(np.int16)
print(arr.dtype)
print(arr.size)
print(arr)

In [ ]:
#dictionary
dc={'a': 10, 'b':30, 'c': 40}
keys=dc.keys()
values=dc.values()
print(values)
items=dc.items()
print(items)

#KEYS TO NDARRAY
arr=np.array(list(keys)) ##DATA TYPE CONVERSION FROM OBJECT TO STRING
print(type(arr))
print(arr.dtype)
arr=arr.astype("U32")
print(arr.dtype)
print(arr.size)
print(arr)

In [ ]:
#VALUES TO NDARRAY
arr=np.array(list(values))
print(arr)
arr=arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#items to ndarray
arr=np.array(list(items))
print(arr)
## arr=arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

### Creataing ndArray from scratch

In [12]:
#ndarray
import numpy as np
arr= np.zeros((2,3), dtype=np.int8)
print(arr)
# arr=arr.astype(np.int16)
# print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

print(arr)

[[0 0 0]
 [0 0 0]]
int8
(2, 3)
2
6
[[0 0 0]
 [0 0 0]]


In [13]:
#zeros_like
arr=np.zeros_like(arra2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
int64
(3, 2, 4)
3
24


In [ ]:
#np.ones
arr= np.ones((3,3,3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#ones_like
arr=np.ones_like(arra2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [14]:
#np.empty
arr=np.empty((4,3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12


In [15]:
arr=np.empty_like(arra2) #arra2 er shape onujayi hobe
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
int64
(3, 2, 4)
3
24


In [16]:
#np.full
arr=np.full((4,3), np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


In [ ]:
# shape jana na thakle
arr=np.full_like(arra2, np.inf, dtype=np.float64)
arr=np.full_like()
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

## array Generation with random values

In [ ]:
#np.random.rand(shape)
arr=np.random.rand(2,3) # 0-->1 porjonto value dey generate kore
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#np.random.randint((start, end, (shape))
arr=np.random.randint(1,100,(2,3)) # starting point, end point, ki shape er data chacchi
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#np.random.uniform((start, end(shape))
# 
arr=np.random.uniform(50, 100, (3,4)) # 0-->1 porjonto value dey generate kore
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#np.range(start, end, step) -> similar to range function
arr = np.arange(1,10, 1)
print(arr)
print("Now Reshaping it")
matrix=arr.reshape(3,3)
print(matrix)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#np.linespace(start, end(included), koita) create values in equal distance over the end point
arr=np.linspace(1,15,10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# np. logspace(start exponent, end exponent, exponenet step)
arr=np.logspace(2,8,11) # exponent step= (start - end)/(step-1) 
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
arr=np.logspace(0, 4,2, base=2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


## creating diagonal and identity matrix

In [ ]:
diagonal_matrix=np.diag([1,2,3])
print(diagonal_matrix)
print(diagonal_matrix.shape)

In [ ]:
#identity matrix
id_matrix=np.eye(4,4)
print(id_matrix)
print(id_matrix.shape)
#np.eye(row, colomn)
mat=np.eye(3,4,-1) # ekta step niche neme jabe diagonal gulaa
print(mat)
a=np.eye(3)
print(a)

# indexing and slicing 

In [ ]:
#indexing
print(ara1)
print(arra1)
print(ara1[2])
print(arra1[1][2])
arra1[1][2]=100
print(arra1[1][2])


In [ ]:
#slicing
#1d= arr[start: end: step]
ara1_mod=ara1[1:4]
print(ara1_mod)


In [ ]:
#2d slicing
# arr[row_start: row_end : step: ,column_start: column_end: step]

arra1_mod= arra1[0: 1, ]
print(arra1_mod)
arra1_mod=arra1[1: ,]
print(arra1_mod)
#gettin column
array_c=arra1[::, 0:1]

print(array_c)
array_c= arra1[: :, 1: 2]
print(array_c)


#getting a portion

portion=arra1[::, 0:2]
print(portion)

# advanced indexing and slicing

In [ ]:
ara1_mod=ara1[1:4].copy()
ara1[1]=100
print(ara1_mod)
print(ara1)


In [ ]:
lst=np.array([10,20,30,40])
values= lst[[1,3]]
print(values)

In [ ]:
print(arra1)
print(arra1[[0,1], [1,2]])
print(arra1[arra1>2])
arra1[arra1>2]=0
print(arra1)

In [ ]:
arr=np.array([[10,20,30], [40,50,70]])
#iteration
# for i in arr:
#     for j in i:
#         print(j)
for i in np.nditer(arr):
    print(i)
