In [3]:
import numpy as np 
arr= np.random.randint(1,100,size=(10,5)) # sample-10, feature 5( column)
arr.shape

(10, 5)

In [4]:
b=arr.reshape(5,10)
b.shape
b.ndim
b

array([[18, 18, 98, 68, 91, 40, 41, 49, 43, 90],
       [74, 38, 65, 98, 72, 55, 45,  3, 99, 96],
       [96, 14, 80, 93, 75, 54, 77, 18, 77, 66],
       [ 8, 59, 77, 87, 37, 56, 46, 52, 22,  4],
       [43, 75, 65, 21, 96, 55, 69, 57, 62, 72]], dtype=int32)

In [5]:
## row wise flattening 
flatten=b.flatten()
print(flatten)
print(flatten.ndim)

[18 18 98 68 91 40 41 49 43 90 74 38 65 98 72 55 45  3 99 96 96 14 80 93
 75 54 77 18 77 66  8 59 77 87 37 56 46 52 22  4 43 75 65 21 96 55 69 57
 62 72]
1


In [10]:
## column wise flattening
column_wise_flattening= np.ravel(b, order='F')
print(column_wise_flattening)

[21 22 21 29 24 20]


In [11]:
a= np.random.randint(1,10,size=(2,3)) 
b= np.random.randint(20,30,size=(2,3)) 
print(a)
print(b)

[[5 6 5]
 [5 2 4]]
[[28 27 28]
 [24 24 20]]


## concatenate

In [8]:
con_row= np.concatenate((a,b), axis=0) # column same thaka lagbe
print(con_row)
con_col= np.concatenate((a,b), axis=1) # row same thaka lagbe otherwise error asbe
print(con_col)

[[ 4  3  4]
 [ 7  6  9]
 [21 21 24]
 [22 29 20]]
[[ 4  3  4 21 21 24]
 [ 7  6  9 22 29 20]]


In [9]:
# error
x= np.random.randint(1,10,size=(2,3)) 
y= np.random.randint(20,30,size=(1,3)) 
r=np.concatenate((x,y), axis=1) ## row same nai oijonno error dekhai
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
# transpose
matrix= np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
mat_transpose=matrix.T
print(mat_transpose)
mat_again_transpose= mat_transpose.T
print(mat_again_transpose)

## Splitting

In [ ]:
x= np.random.randint( 1, 10, size=(10,))
split_array=np.array_split(x, 3) 
print(split_array)
print("now splitting in eqully.\n")

## equally split korar jonno split function use korley hoto
y= np.random.randint(1, 100, size=(21, ))
split_equally= np.split(y, 3)
print(split_equally)

## Mathematical Function


In [12]:
x=np.array([10,20,30])
y=np.array([60,70,80])
Z= np.array([10, 20,30,np.nan, 100, np.nan]) ## normallyy  calculate korle eita nan e asbe, oijonno nan function use kora lage
add=x+y
print(add)
mul=x*y
print(mul)
sub=x-y
print(sub)
div=x/y
print(div)
print(np.reciprocal(x))
print(np.pow(x,y))
print(np.mod(x, y))

print(np.sum(x))
print(np.cumulative_sum(x))
print(np.prod(x)) ## return the product of array elements over a given axis
print(np.nanprod(Z)) ## Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones
print(np.cumulative_prod(x)) ## Return the cumulative product of elements along a given axis
print(np.cumprod(x)) ## another way to do that
print(np.cross(x, y))
print(np.diff(x)) ## describe the difference between the elements


[ 70  90 110]
[ 600 1400 2400]
[-50 -50 -50]
[0.16666667 0.28571429 0.375     ]
[0 0 0]
[1152921504606846976                   0                   0]
[10 20 30]
60
[10 30 60]
6000
600000.0
[  10  200 6000]
[  10  200 6000]
[-500 1000 -500]
[10 10]


## Exponents and Logarithms

In [ ]:
print(np.exp(x))
print(np.exp2(x)) ## Calculate 2**p for all p in the input array
print(np.log10(x))
print(np.log2(x))
print("\n")
print(np.lcm(x, y))
print(np.gcd(x,y))

## Trigonometry

In [ ]:
print(np.sin(x))
print(np.cos(x))
print(np.tan)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.rad2deg(x))
print(np.sinh(x))
print(np.asinh(x))

## more Mathematical Function

In [ ]:
print("eto beshi kora lagbe na, engough kore felecho baba, keep practising more")

In [ ]:
a=np.array([4,1,2])
print(np.sort(a))
c=np.array([4,5,6])
print(a+c)

print(np.sin(np.pi/2))
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

## Broadcasting

In [14]:
a=np.array([1,2,3,4]) ## hence we call it vector
print(a+10)

## braodcasting in 2d arrays
matrix= np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
result=matrix+2
print(result)
vector=np.array([12,13,14,15])
print(matrix+vector) ## column size and vector size must be same



[11 12 13 14]
[[12 22 32 42]
 [52 62 72 82]]
[[22 33 44 55]
 [62 73 84 95]]


## comparison operator

In [ ]:
## here  is some logical operator >, <, =>, >= , ==, != 

x=np.array([10,20,300])
y=np.array([60,70,80])
result= x<y
print(result)
print(x>y)
print(x==y)
print(np.all(x>y)) ## sobgulai howa lagbe\
print(np.any(x>y)) ## jekono ekta holey hobe
print(x!=y)
print(x>=y)

array1 = np.array([9, 12, 21])
array2 = np.array([21, 12, 9])
result=np.greater(array1, array2)
print("is greater: ", result)
result=np.less(array1,array2)
print("is less: ", result)
result=np.greater_equal(array1, array2)
print("is greater equeal: " , result)

## Logical function

In [ ]:
x1=np.array([True, False, True])
x2=np.array([False, False, True])
print(np.logical_and(x1,x2))
print(np.logical_or(x1,x2))
print(np.logical_not(x1,x2))


## Sorting

In [15]:
## In place Sorting
array1 = np.array([90, 12, 21])
array2 = np.array([21, 12, 9])
array3=array1.copy()
array3.sort()
print("Here is now in place sorting: ")
print(array3)
print("\n")
print("here is now copy sorting: ")
array_copy=np.sort(array1)
print(array_copy, "\n")

## 2d array sorting np.sort(a, axis= default -1 that means last axis, kind= ki dhoroner sorting, order= ki order e sort korbo, stable= ) 

## row wise horizontally
array=np.array([[100, 20,2, 35],
               [22,234,2,45]])
print("horizontally: ", np.sort(array, axis=1))
print("Vertically: ", np.sort(array, axis=0))
 ## sort the flattened array
print(np.sort(array, axis=None)     # sort the flattened array
)


print("\n another one: \n")

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
print(np.sort(a, order='height'))

Here is now in place sorting: 
[12 21 90]


here is now copy sorting: 
[12 21 90] 

horizontally:  [[  2  20  35 100]
 [  2  22  45 234]]
Vertically:  [[ 22  20   2  35]
 [100 234   2  45]]
[  2   2  20  22  35  45 100 234]

 another one: 

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]


## Searching

In [ ]:
x=np.random.randint(1,100, size=(10,10))
print(x)
print(np.where(x==10))

In [ ]:
x=np.array( [
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
    [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
    [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
    [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
])
print(np.where(x==3))
print(np.where(x>95))
max=np.argmax(x)
min=np.argmin(x)
y=np.where(x>95, 90, 5)
print(np.where(x>95, 90, 5))

## where(condition, if true replace it , otherwise replace with this)

## Counting

In [ ]:
a=np.count_nonzero(y>=90)
b=np.count_nonzero(y<=5)

print(a)
print(b)
unique, count= np.unique(y, return_counts=True)
print(unique)

## Statistical Function

In [ ]:
data=np.genfromtxt('student_scores.csv',delimiter=',', skip_header=1)
math_mark=data[:,2]
print(math_mark)
print(np.median(math_mark))
print(np.std(math_mark))
study_hours=np.array([5.3, 3.5, 3, 6, 7.5, 8])
exam_scores=np.array([70, 55, 50, 75, 83, 90])
print(np.corrcoef(study_hours, exam_scores))


## linear Algebra

In [ ]:
matrix=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(matrix)
matrix2 = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print(matrix2)
print("\nDot product of matrix, matrix1: \n", np.dot(matrix, matrix2))
print("Trace: ", np.trace(matrix))
print("Determinant: ", np.linalg.det(matrix))